name: Build and Deploy

on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@main
        
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: '8.0.x'
      
      - name: Build with .NET
        run: dotnet build -c Release
      
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        
      - name: Packing
        run: dotnet pack ./MedTheMediator/MedTheMediator.csproj -c Release
      
      - name: Publishing
        run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.NUGET_SECRET }} -s https://api.nuget.org/v3/index.json